### PR TITLE
Example of Looping Functions

### PR DESCRIPTION
**Pull request by restrellado**
This pull request loops the functions over four quarters of 2016. The output is a data frame of the average spending in categories for each 2016 quarter. The files are read in [directly from ProPublica](https://projects.propublica.org/represent/expenditures) so we can take advantage of the file naming convention: `https://projects.propublica.org/congress/assets/staffers/[YEAR][QUARTER]-house-disburse-detail.csv`

The functions in this example include the following

- Read in the data 
- Add the file names 
- Calculate the means for each category and quarter

I included the `csv` for inspection. 

If this approach is useful, we can easily loop it over additional quarters and use different summarizing functions.

### CODE REVIEW

**Comment by dwillis** [comment]
This looks like a very useful thing.

**Comment by restrellado** [comment]
Let's try it with more data. I'll add another set of quarters. Is mean spending in a category useful or should we try something else?

**Comment by dwillis** [comment]
I think mean spending in a category is useful, yes.

**Comment by supermdat** [comment]
There's nothing inherently wrong with the code or the computations - they do exactly what you intended.

But I added an example code chunk at the end of your code to show that even basic summary stats like these will provide undesirable results if we don't clean the data first. 

load `plyr` (before `tidyverse`), then run the code chunk beginning in line 84 and you'll see variations of spelling for "Rent, Communication, Utilities."  These spelling variations result in undesirable summary stats (i.e., avg spending for each spelling variation separately)

**Comment by restrellado** [comment]
So right. Thanks for spotting that problem. So maybe we loop one of your cleaning scripts across the datasets before calculating the mean?

**Comment by supermdat** [comment]
Apologies about the delay.

Most def.  Feel free to use the output of any of the cleaning scripts.  I believe the last one (before today) was `9_NB_CleanChrVar_Payee.Rmd`.  Just as a refresh, the way that they were written, each has to be run in sequence (e.g., 1_..., 2_..., etc.).  They all run pretty quickly if I remember right, except for `9_NB_CleanChrVar_Payee.Rmd`.

Also, just today I created to quick PRs to give you a better dataset to work with. #39 cleans up the dates, and #40 adjusts `amount` for inflation.  As with the others, each takes the output of the previous code as an starting input. So #39 starts with the result of `9_NB_CleanChrVar_Payee.Rmd`, and #40 starts with the result of #39.

I'm thinking it might be better to simply create a saved .csv of the output and place it somewhere (data.world?), but I'd like your thoughts.

**Pull request closed without merging**
